# Generated by Django 3.2.4 on 2021-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_alter_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
